openapi: "3.0.3"
info:
  description: "This is a training exercise for a Pokedex server. For this sample, you can use the api key `special-key` to test the authorization filters."
  version: "1.0.0"
  title: "Swagger Pokedex"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "pokemon"
    description: "everything about your pokemons"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
paths:
  /dataservice/ping:
    get:
      tags:
        - Ping
      summary: pings the service to check its health
      operationId: ping
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string
                example: i'm alive
        404:
          description: service unavailable
  /dataservice/v1/pokemon:
    post:
      tags:
        - pokemon
      summary: create a pokemon object in database
      operationId: getPokemon
      parameters:
        - in: header
          name: apiKey
          description: the unique api key for this server
          schema:
            type: string
          required: true
      requestBody:
        description: get pokemon request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePokemonRequest'
        required: true
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePokemonResponse'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
components:
  schemas:
    CreatePokemonRequest:
      type: object
      required:
        - parametro1
      properties:
        parametro1:
          $ref: '#/components/schemas/parametro1'

    CreatePokemonResponse:
      type: object
      required:
        - parametro1
      properties:
        parametro1:
          $ref: '#/components/schemas/parametro1'

    ErrorInfo:
      type: object
      required:
        - parametro1
      properties:
        parametro1:
          $ref: '#/components/schemas/parametro1'

    parametro1:
      type: string
      description: primeiro parametro
      example: 'xalala'

                